import 'package:drift/drift.dart';

/// Auto-generated topic clusters.
class ClustersTable extends Table {
  @override
  String get tableName => 'clusters';

  TextColumn get id => text()();

  /// Human-readable name — auto-generated by LLM, editable by user.
  TextColumn get name => text()();

  /// Hex colour string e.g. '#7C4DFF'.
  TextColumn get colorHex => text()();

  IntColumn get createdAt => integer()();

  @override
  Set<Column> get primaryKey => {id};
}
