include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
    strict-inference: false
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    todo: ignore
    avoid_dynamic_calls: ignore
    deprecated_member_use: ignore
    unawaited_futures: ignore
    use_build_context_synchronously: ignore
    inference_failure_on_function_invocation: ignore
    unused_field: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - use_super_parameters
